// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/WidgetSettingPage.html":'\x3cdiv class\x3d"widget-setting-page"\x3e\r\n  \x3cdiv class\x3d"section common-setting" data-dojo-attach-point\x3d"commonSettingNode"\x3e\r\n    \x3cdiv class\x3d"basic"\x3e\r\n      \x3cdiv class\x3d"icon jimu-float-leading"\x3e\r\n        \x3cimg class\x3d"real-icon"  data-dojo-attach-point\x3d"iconNode"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv class\x3d"right jimu-float-trailing jimu-leading-margin1"\x3e\r\n        \x3cinput data-dojo-type\x3d"dijit/form/ValidationTextBox" data-dojo-attach-point\x3d"labelNode" placeholder\x3d"${nls.widgetLabel}" required\x3d"true" class\x3d"widget-setting-input" tabindex\x3d"0"\x3e\r\n        \x3cdiv class\x3d"right-foot" data-dojo-attach-point\x3d"rightFooterNode"\x3e\r\n          \x3cdiv class\x3d"image-container"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"imageChooserPlaceholder"\x3e\x3c/div\x3e\r\n            \x3c!-- \x3cspan nowrap class\x3d"change-icon" data-dojo-attach-point\x3d"changeNode"\x3e${nls.changeIcon}\x3c/span\x3e --\x3e\r\n            \x3ca class\x3d"help-link jimu-float-trailing" target\x3d"_blank" data-dojo-attach-point\x3d"helpNode"\x3e${nls.more}\x3c/a\x3e\r\n          \x3c/div\x3e\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"layout"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"section widget-setting" data-dojo-attach-point\x3d"widgetSettingNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/config dojo/Deferred dojo/request dojo/topic dojo/aspect dojo/on dojo/mouse dojo/query dojo/string dojo/NodeList-dom dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./WidgetSettingPage.html ./WidgetDefaultSettingPage jimu/utils jimu/WidgetManager jimu/portalUrlUtils jimu/portalUtils jimu/dijit/ViewStack jimu/dijit/ImageChooser jimu/dijit/LoadingIndicator jimu/dijit/Message dijit/form/CheckBox esri/request".split(" "),
function(u,c,d,I,n,v,l,w,J,q,K,L,x,M,y,z,A,B,C,h,r,t,N,O,f,D,E,P,F){var p="en de es fr ja ru zh-cn zh-tw zh-hk ar it ko pl pt-br pt-pt ro".split(" "),G=[],m=null;return u([y,z,A],{templateString:B,startup:function(){this.inherited(arguments);this.own(l("builder/widgethelp.json",{handleAs:"json"}).then(function(a){m=a},function(a){console.error(a)}).always(c.hitch(this,function(){this.domNode&&(this.own(q(window,"resize",c.hitch(this,this.resize))),this.init())})))},init:function(){this.loading=new D;
d.addClass(this.loading.domNode,"load-widget-setting");this.loading.placeAt(this.widgetSettingNode);this.initCommonAttr();this.initWidgetAttr();this.resize()},resize:function(){var a=d.getContentBox(this.domNode);d.setStyle(this.widgetSettingNode,{height:a.h-94+"px"})},onCancel:function(){this.onClose();this.popup.close()},onOk:function(){var a=this._checkLabelExist();if(a)return new E({message:a}),!1;this.imageChooser.imageData&&(this.setting.icon=this.imageChooser.imageData);this.setting.label=
h.sanitizeHTML(this.labelNode.get("value"));if(this.settingDijit){var b=this.settingDijit.getConfig(!0);if(!1===b)return!1;b&&"function"===typeof b.then?b.then(c.hitch(this,function(a){if(!1===a)return!1;var b=this.settingDijit.getDataSources();b&&"function"===typeof b.then?b.then(c.hitch(this,function(b){this.setting.config=a;this.setting.provideDataSources=b;this._closeSettingPopup()})):(this.setting.config=a,this.setting.provideDataSources=b,this._closeSettingPopup())})):(a=this.settingDijit.getDataSources())&&
"function"===typeof a.then?a.then(c.hitch(this,function(a){this.setting.config=b;this.setting.provideDataSources=a;this._closeSettingPopup()})):(this.setting.config=b,this.setting.provideDataSources=a,this._closeSettingPopup())}else this._closeSettingPopup()},_closeSettingPopup:function(){delete this.setting.isDefaultConfig;w.publish("widgetSettingPageOk",this.setting,this.fromNode);this.onClose();this.popup.close()},_checkLabelExist:function(){var a=0,b=this.labelNode.get("value");if(""===x.trim(b))return this.nls.labelRequired;
var H=h.getControllerWidgets(this.appConfig);this.appConfig.visitElement(c.hitch(this,function(c){this.setting.id!==c.id&&c.label===b&&(0<H.length?a++:c.isOnScreen&&a++)}));return 0<a?this.nls.labelExists:""},onClose:function(){this.popup&&this.popup.closeBtnNode&&this.popup.closeBtnNode.focus();this.settingViewStack?(this.settingDijitUI.destroy(),this.settingDijitJSON.destroy(),this.settingViewStack.destroy()):this.settingDijit&&this.settingDijit.destroy()},_isInSupportLanguages:function(){var a=
!1,b=n.locale.toLowerCase();if(-1<p.indexOf(b))a=!0;else for(var c=0;c<p.length;c++)if(b.split("-")[0]===p[c].split("-")[0]){a=!0;break}return a},_getHelpLink:function(a,b){var d=new v,e=null;a=a.toLowerCase();b="html"===(b||"html").toLowerCase()?"widgets2d":"widgets3d";if(window.isXT)l("/webappbuilder/help/exists",{handleAs:"json"}).then(c.hitch(this,function(g){g&&g.exists?l("/webappbuilder/help/cxhelp.js",{handleAs:"json"}).then(c.hitch(this,function(g){var f="#";e=c.getObject("dev."+b+"."+a,!1,
m);g&&g.m&&e&&g.m[e]?f="/webappbuilder/help/"+g.m[e]:e&&(f="/webappbuilder/help/"+e);d.resolve(f)}),c.hitch(this,function(a){console.warn(a);d.resolve("#")})):d.resolve("#")}),function(a){console.error(a);d.resolve("#")});else{var k=t.getPortalUrlFromLocation();if(-1<k.indexOf("arcgis.com")){var f="#",e=c.getObject("online."+b+"."+a,!1,m);"widgets3d"===b||-1<G.indexOf(a)||!this._isInSupportLanguages()?(e&&(f="http://"+(-1<k.indexOf("maps.arcgis.com")?"doc":"docdev")+".arcgis.com/en/web-appbuilder/create-apps/"+
e),d.resolve(f)):(f={url:t.getPortalSelfInfoUrl(k),content:{f:"json",culture:n.locale},handleAs:"json",callbackParamName:"callback",preventCache:!0},F(f).then(c.hitch(this,function(a){var b="#";if(a&&a.helpBase&&e)try{b=a.helpBase.split("/").slice(0,4).join("/")+"/web-appbuilder/create-apps/"+e}catch(Q){b="http://doc.arcgis.com/en/web-appbuilder/create-apps/"+e}d.resolve(b)}),c.hitch(this,function(a){console.warn(a);d.resolve("#")})))}else{var h=n.locale||"en",e=c.getObject("portal."+b+"."+a,!1,m);
l(k+"sharing/rest/portals/helpmap?f\x3djson",{handleAs:"json"}).then(c.hitch(this,function(a){var b="#";a&&a.helpMap&&a.helpMap.m&&e&&a.helpMap.m[e]&&(b=k+"portalhelp/"+h+"/"+a.helpMap.m[e]);d.resolve(b)}),c.hitch(this,function(a){console.warn(a);d.resolve("#")}))}}return d},initCommonAttr:function(){var a=h.processUrlInAppConfig(this.setting.icon);d.setAttr(this.iconNode,"src",a);window.isRTL&&this.setting.mirrorIconForRTL&&d.addClass(this.iconNode,"jimu-flipx");this.labelNode.set("value",this.setting.label);
this._getHelpLink(this.setting.name,c.getObject("manifest.platform",!1,this.setting)).then(c.hitch(this,function(a){"#"!==a&&(d.setStyle(this.helpNode,"display","inline-block"),d.setAttr(this.helpNode,"href",a))}));this.imageChooser=new f({goldenWidth:24,goldenHeight:24,format:[f.GIF,f.JPEG,f.PNG],label:this.nls.changeIcon},this.imageChooserPlaceholder);d.addClass(this.imageChooser.domNode,"jimu-float-leading");!1===this.setting.inPanel&&!0===this.setting.isOnScreen&&!0!==this.setting.closeable?(this.imageChooser.disableChooseImage(),
d.setAttr(this.imageChooser.domNode,"title",this.nls.unableChangeIcon)):(this.imageChooser.enableChooseImage(),this.own(q(this.imageChooser,"imageChange",c.hitch(this,function(a){this.iconNode.src=a;this.setting.icon=a}))))},initWidgetAttr:function(){!1===this.setting.hasConfig?this.widgetSettingNode.innerHTML='\x3cdiv class\x3d"noconfig-info"\x3e'+this.nls.noConfig+"\x3c/div\x3e":r.getInstance().tryLoadWidgetConfig(this.setting).then(c.hitch(this,function(a){this.setting.hasSettingPage?r.getInstance().loadWidgetSettingPage(this.setting).then(c.hitch(this,
function(a){this.widgetSettingNode?(this.settingDijit=a,this.settingDijit.settingPagePopup=this.popup,d.place(this.settingDijit.domNode,this.widgetSettingNode),this.settingDijit.startup(),this.loading.destroy(),d.setAttr(this.widgetSettingNode,"data-widget-loaded","true")):a.destroy()})):this.widgetSettingNode&&(this.settingDijit=new C({config:this.setting.config}),d.place(this.settingDijit.domNode,this.widgetSettingNode),this.settingDijit.settingPagePopup=this.popup,this.settingDijit.startup(),this.loading.destroy())}))},
setAppConfig:function(a){this.appConfig=a}})});